## DRONE PATH CALCULATOR

LOG_PATH = "modes/followmode/log_test_curve2.txt"
DRONE_ACTIVATED = False
DRONE_ACTIVATED_UI = False
AVERAGE_STRATING_HEIGHT = 110
FULLSCREEN_ON = False
CROSS_DISTANCE = 200
# GATE_DISTANCE = CROSS_DISTANCE / 2
GATE_DISTANCE = 150